import pandas as pd
import numpy as np
import copy
from fair import FAIR
from fair.io import read_properties
from fair.interface import fill, initialise
from scipy.interpolate import interp1d
import pickle

# Processes data for Fig S1 - but don't need to run this as the ouptut is saved already
# and the input csv is too big.

# This takes all the scenarios in the AR6 database which have the full set 
# of FaIR species, and generates their forcing, concentrations, emissions using FaIR.
# If a scenario is generated by multiple models (IAMs), treat as separate scenarios.

# This is done to allow for the prediction of a target variable to be done
# over all scenarios in the database. 
# Needs the IIASA AR6 database, which is too big to store here

datadir = 'data'

df = pd.read_csv(f"{datadir}/AR6_Scenarios_Database_World_ALL_CLIMATE_v1.1.csv")

# get full set of scenarios

scenarios_list = []
for index, row in df.iterrows():
    scenarios_list.append(row[1])
    
scenarios_set = set(scenarios_list)
scenarios_set_list = list(scenarios_set)

# get dictionary with the models for each scenario

scens_models = {}
for scen in scenarios_set_list:
    if scen not in scens_models.keys():
        scen_data = df.loc[(df['Scenario'] == scen),"Model"]
        scen_model_list = set(scen_data.values)
        scens_models[scen] = scen_model_list


# set species, alternate names in csv, and get set of scenarios with all ems
species_ems = ['CO2 FFI', 'CO2 AFOLU', 'CH4', 'N2O', 'Sulfur', 'BC', 'OC', 'NH3', 'NOx',
 'VOC', 'CO', 'CFC-11', 'CFC-12', 'CFC-113', 'CFC-114', 'CFC-115', 'HCFC-22',
 'HCFC-141b', 'HCFC-142b', 'CCl4', 'CHCl3', 'CH2Cl2', 'CH3Cl', 'CH3CCl3', 'CH3Br',
 'Halon-1202', 'Halon-1211', 'Halon-1301', 'Halon-2402', 'CF4', 'C2F6', 'C3F8',
 'c-C4F8', 'C4F10', 'C5F12', 'C6F14', 'C7F16', 'C8F18', 'NF3', 'SF6', 'SO2F2',
 'HFC-125', 'HFC-134a', 'HFC-143a', 'HFC-152a', 'HFC-227ea', 'HFC-23', 'HFC-236fa',
 'HFC-245fa', 'HFC-32', 'HFC-365mfc', 'HFC-4310mee']

alternate_species_names = {
    'CO2|Energy and Industrial Processes':'CO2 FFI',
    'CO2|AFOLU':'CO2 AFOLU',
    'CFC11':'CFC-11',
    'CFC12':'CFC-12',
    'CFC113':'CFC-113',
    'CFC114':'CFC-114',
    'CFC115':'CFC-115',
    'HCFC22':'HCFC-22',
    'HCFC141b':'HCFC-141b',
    'HCFC142b':'HCFC-142b',
    'Halon1202':'Halon-1202',
    'Halon1211':'Halon-1211',
    'Halon1301':'Halon-1301',
    'Halon2402':'Halon-2402',
    'PFC|CF4':'CF4',
    'PFC|C2F6':'C2F6',
    'PFC|C3F8':'C3F8',
    'PFC|cC4F8':'c-C4F8',
    'PFC|C4F10':'C4F10',
    'PFC|C5F12':'C5F12',
    'PFC|C6F14':'C6F14',
    'PFC|C7F16':'C7F16',
    'PFC|C8F18':'C8F18',
    'HFC|HFC125':'HFC-125',
    'HFC|HFC134a':'HFC-134a',
    'HFC|HFC143a':'HFC-143a',
    'HFC|HFC152a':'HFC-152a',
    'HFC|HFC227ea':'HFC-227ea',
    'HFC|HFC23':'HFC-23',
    'HFC|HFC236fa':'HFC-236fa',
    'HFC|HFC245ca':'HFC-245fa',
    'HFC|HFC32':'HFC-32',
    'HFC|HFC365mfc':'HFC-365mfc',
    'HFC|HFC43-10':'HFC-4310mee',
    }

alternate_species_names_rev = {
    'CO2 FFI':'CO2|Energy and Industrial Processes',
    'CO2 AFOLU':'CO2|AFOLU',
    'CFC-11':'CFC11',
    'CFC-12':'CFC12',
    'CFC-113':'CFC113',
    'CFC-114':'CFC114',
    'CFC-115':'CFC115',
    'HCFC-22':'HCFC22',
    'HCFC-141b':'HCFC141b',
    'HCFC-142b':'HCFC142b',
    'Halon-1202':'Halon1202',
    'Halon-1211':'Halon1211',
    'Halon-1301':'Halon1301',
    'Halon-2402':'Halon2402',
    'CF4':'PFC|CF4',
    'C2F6':'PFC|C2F6',
    'C3F8':'PFC|C3F8',
    'c-C4F8':'PFC|cC4F8',
    'C4F10':'PFC|C4F10',
    'C5F12':'PFC|C5F12',
    'C6F14':'PFC|C6F14',
    'C7F16':'PFC|C7F16',
    'C8F18':'PFC|C8F18',
    'HFC-125':'HFC|HFC125',
    'HFC-134a':'HFC|HFC134a',
    'HFC-143a':'HFC|HFC143a',
    'HFC-152a':'HFC|HFC152a',
    'HFC-227ea':'HFC|HFC227ea',
    'HFC-23':'HFC|HFC23',
    'HFC-236fa':'HFC|HFC236fa',
    'HFC-245fa':'HFC|HFC245ca',
    'HFC-32':'HFC|HFC32',
    'HFC-365mfc':'HFC|HFC365mfc',
    'HFC-4310mee':'HFC|HFC43-10',
    }


scen_models_with_all_ems = {}
for scen in scens_models.keys():
    print('\n')
    print(scen)
    models_with_all_ems = []
    for model in scens_models[scen]:
        print(model)
        scen_array = df.loc[(df['Scenario'] == scen) & (df['Model'] == model)]
        
        common_specs = []
        for index, row in scen_array.iterrows():
            if "AR6 climate diagnostics|Infilled|Emissions|" in row[3]:
                file_spec = row[3].split("AR6 climate diagnostics|Infilled|Emissions|")[1]
                if file_spec in species_ems:
                    common_specs.append(file_spec)
                elif file_spec in alternate_species_names.keys():
                    if alternate_species_names[file_spec] in species_ems:
                        common_specs.append(alternate_species_names[file_spec])
        ok_flag = 1
        for spec in species_ems:
            if spec not in common_specs:
                print(f'Missing: {spec}')
                ok_flag = 0 
        if ok_flag == 1:
            models_with_all_ems.append(model)
    scen_models_with_all_ems[scen] = models_with_all_ems
    
total_nr_models_scens = 0
for scen in scens_models.keys():
    total_nr_models_scens += len(scens_models[scen])

total_nr_models_scens_with_all_ems = 0
for scen in scens_models.keys():
    total_nr_models_scens_with_all_ems += len(scen_models_with_all_ems[scen])
        
print(f'{np.around(100*total_nr_models_scens_with_all_ems/total_nr_models_scens, decimals=0)} % of scenario-model pairs have all emissions')

 
# run ssp119 in FaIR to get 2015 restart
# and to check ems etc are right units from csv

f2 = FAIR()

f2.define_time(1750, 2015, 1)

scenarios = ['ssp119']
f2.define_scenarios(scenarios)

configs = ['test']
f2.define_configs(configs)

species, properties = read_properties()
f2.define_species(species, properties)

f2.allocate()
f2.fill_species_configs()
f2.fill_from_rcmip()

initialise(f2.concentration, f2.species_configs['baseline_concentration'])
initialise(f2.forcing, 0)
initialise(f2.temperature, 0)
initialise(f2.cumulative_emissions, 0)
initialise(f2.airborne_emissions, 0)

capacities = [4.22335014, 16.5073541, 86.1841127]
kappas = [1.31180598, 2.61194068, 0.92986733]
epsilon = 1.29020599
fill(f2.climate_configs['ocean_heat_capacity'], capacities)
fill(f2.climate_configs['ocean_heat_transfer'], kappas)
fill(f2.climate_configs['deep_ocean_efficacy'], epsilon)

f2.run()



# run scens in FaIR in one go, output info
units_factor = {
    'CO2 FFI':1e-3, 
    'CO2 AFOLU':1e-3,
    'N2O':1e-3,
    }

rcmip_forcing_file = f'{datadir}/rcmip-radiative-forcing-annual-means-v5-1-0.csv'
species_forcing = ['Solar', 'Volcanic']
df_forc = pd.read_csv(rcmip_forcing_file)


scen_model_full_list = []
for scen in scen_models_with_all_ems.keys():
    for model in scen_models_with_all_ems[scen]:
        scen_model = scen + '___' + model
        scen_model_full_list.append(scen_model)

f = FAIR()

f.define_time(2015, 2100, 1)

f.define_scenarios(scen_model_full_list)

configs = ['test']
f.define_configs(configs)

species, properties = read_properties()
f.define_species(species, properties)

f.allocate()
f.fill_species_configs()
# f.fill_from_rcmip()  # instead of this, fill from the csv


emis_array = np.zeros((85, len(scen_model_full_list), 1, 64))

for sm_i, scen_model in enumerate(scen_model_full_list):
    print(f'{sm_i}: {scen_model}')
    scen, model = scen_model.split("___")
        
    for specie in species_ems:
        spec_name = copy.deepcopy(specie)
        if specie in alternate_species_names_rev.keys():
            spec_name = copy.deepcopy(alternate_species_names_rev[specie])
        emis_in = df.loc[(df['Scenario'] == scen) & 
                         (df['Model'] == model) & 
                         (df['Variable'] == "AR6 climate diagnostics|Infilled|Emissions|" + spec_name),
                         "2015":"2100"].interpolate(axis=1).values.squeeze()
       
        notnan = np.nonzero(~np.isnan(emis_in))
        
        rcmip_index = np.arange(2014.5, 2100.5)
        interpolator = interp1d(
            rcmip_index[notnan],
            emis_in[notnan],
            fill_value="extrapolate",
            bounds_error=False,
        )
        emis = interpolator(f.timepoints)

        factor = 1
        if specie in units_factor.keys():
            factor = units_factor[specie]
         
        
        emis_array[:,sm_i,0,species.index(specie)] = emis*factor
            
            
fill(f.emissions, emis_array)
        
forc_array = np.zeros((86, len(scen_model_full_list), 1, 64))

for specie in species_forcing:
    spec_name = copy.deepcopy(specie)
    forc_in = df_forc.loc[(df_forc['Scenario'] == 'ssp370') &
                          (df_forc['Variable'].str.endswith("|" + spec_name)) &
                          (df_forc["Region"] == "World"),
                          "2015":"2100"].interpolate(axis=1).values.squeeze()
   
    notnan = np.nonzero(~np.isnan(forc_in))
    
    rcmip_index = np.arange(2014.5, 2100.5)
    interpolator = interp1d(
        rcmip_index[notnan],
        forc_in[notnan],
        fill_value="extrapolate",
        bounds_error=False,
    )
    forc = interpolator(f.timebounds)

    for i in np.arange(len(scen_model_full_list)):
        forc_array[:,i,0,species.index(specie)] = forc

fill(f.forcing, forc_array)

initialise(f.concentration, f2.concentration[265,0,0,:].values)
initialise(f.forcing, f2.forcing[265,:,:,:].values)
initialise(f.temperature, f2.temperature[265,:,:,:].values)
initialise(f.cumulative_emissions, f2.cumulative_emissions[265,:,:,:].values)
initialise(f.airborne_emissions, f2.airborne_emissions[265,:,:,:].values)
fill(f.gas_partitions, f2.gas_partitions.values)
initialise(f.alpha_lifetime, f2.alpha_lifetime[265,:,:,:].values)


capacities = [4.22335014, 16.5073541, 86.1841127]
kappas = [1.31180598, 2.61194068, 0.92986733]
epsilon = 1.29020599
fill(f.climate_configs['ocean_heat_capacity'], capacities)
fill(f.climate_configs['ocean_heat_transfer'], kappas)
fill(f.climate_configs['deep_ocean_efficacy'], epsilon)

forcing_temperature_feedback_no_o3 = copy.deepcopy(f.species_configs['forcing_temperature_feedback'])
forcing_temperature_feedback_no_o3.values[0,[i for i ,e in enumerate(species) if e in ['Ozone']]] = 0
fill(f.species_configs['forcing_temperature_feedback'], forcing_temperature_feedback_no_o3)

f.run()


#%%

# save emissions, concentrations, forcings, and the scenario names

full_save_dict  = {}
full_save_dict['Emissions'] = f.emissions.values
full_save_dict['Concentrations'] = f.concentration.values
full_save_dict['Forcing'] = f.forcing.values
full_save_dict['Scenarios'] = scen_model_full_list

#%%
with open(f'{datadir}/scenario_info.pkl', 'wb') as handle:
    pickle.dump(full_save_dict, handle, protocol=pickle.HIGHEST_PROTOCOL)
        
